---
- name: Install Docker on Linuxclient1
  hosts: 192.168.0.34
  become: true

  tasks:
    - name: Install Docker version 24 using yum
      yum:
        name: docker-24:{{ item }}
        state: present
      loop:
        - docker
        - docker-client
        - docker-common
        - docker-rhel-push-plugin
        - docker-scan-plugin
        - docker-latest
