---
- name: Install and Deploy docker on linuxclient1
  hosts: 192.168.0.37
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present

    - name: Install Docker dependencies
      yum:
        name:
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Import Docker GPG key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Install Docker packages (engine)
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Install Python
      yum:
        name:
          - python
        state: present      

    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python /tmp/get-pip.py

    - name: Upgrade pip
      command: pip install --upgrade pip

    - name: Install docker-SDK
      pip:
        name: docker

- name: Deploy Docker Container
  hosts: 192.168.0.37
  become: true

  tasks:
    - name: Pull image and create the container using docker_container
      docker_image:
        name: ernestefrei/devopsproject:latest
        source: pull
    
    - name: Start the container using docker_container
      docker_container:
        name: tomcat_devops
        image: ernestefrei/devopsproject:latest
        state: started
        tty: true
        auto_remove: true
        ports:
          - "8080:8080"
          
    - name: Log out of DockerHub
      docker_login:
        state: absent
